In [1]:
import torch


In [2]:

b = torch.tensor([]).long()
a = torch.tensor([1,2,3]).long()

print(a.dtype)

print(torch.cat((a, b)).dtype)
print(torch.cat((b, a)).dtype)

a.max(dim=-1)

torch.int64
torch.int64
torch.int64


torch.return_types.max(
values=tensor(3),
indices=tensor(2))

In [ ]:
input_ids = torch.tensor(gpt2tokenizer.encode("""Your task is to add calls to a Calendar API to a piece of text.
The API calls should help you get information required to complete the text.
You can call the API by writing "[Calendar()]"
Here are some examples of API calls:
Input: Today is the first Friday of the year.
Output: Today is the first [Calendar()] Friday of the year.
Input: The president of the United States is Joe Biden.
Output: The president of the United States is [Calendar()] Joe Biden.
Input: The current day of the week is Wednesday.
Output: The current day of the week is [Calendar()] Wednesday.
"""))

logits = model(input_ids).logits

sample = gumbel_sample(logits, temperature=0)

gpt2tokenizer.decode(sample[-1])


'Input'

In [394]:
tokens_in = gpt2tokenizer.encode("The quick brown fox jumped over the well in my")

generated = model(torch.tensor(tokens_in).unsqueeze(0))

print(generated.logits.shape)


for beam in enumerate(generated.logits):
    sample = gumbel_sample(beam[1], 0)
    tokens_out = sample.squeeze()
    print(gpt2tokenizer.decode(tokens_out))

print(len(tokens_in))
print(len(tokens_out))


torch.Size([1, 10, 50257])
 first answer fox jumps out the lazy- the head
10
10


In [413]:
generated = model.generate(gpt2tokenizer.encode("""Your task is to add calls to a Calendar API to a piece of text. 
The API calls should help you get information required to complete the text.
You can call the API by writing "[Calendar()]"
Here are some examples of API calls:
Input: Today is the first Friday of the year.
Output: Today is the first [Calendar()] Friday of the year.
Input: The president of the United States is Joe Biden.
Output: The president of the United States is [Calendar()] Joe Biden.
Input: The current day of the week is Wednesday.
Output: """, return_tensors='pt'), max_length=170)

for i, beam in enumerate(generated):
    print(f"{i}: {gpt2tokenizer.decode(beam)}")



The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


0: Your task is to add calls to a Calendar API to a piece of text. 
The API calls should help you get information required to complete the text.
You can call the API by writing "[Calendar()]"
Here are some examples of API calls:
Input: Today is the first Friday of the year.
Output: Today is the first [Calendar()] Friday of the year.
Input: The president of the United States is Joe Biden.
Output: The president of the United States is [Calendar()] Joe Biden.
Input: The current day of the week is Wednesday.
Output:  The current day of the week is Thursday.
Input: The current day of the week is Friday.
Input: The current day of the week is Saturday.
Input: The current day


In [80]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel
gpt2tokenizer = GPT2Tokenizer.from_pretrained('gpt2-medium')
gpt2model = GPT2LMHeadModel.from_pretrained('gpt2-medium')

model = gpt2model
tokenizer = gpt2tokenizer


In [97]:
a = [*map(tokenizer.decode, [[123, 1623, 82, 432, 3284], [123, 1623, 82, 432, 3284]])]
a

['� Colsight Russia', '� Colsight Russia']

In [111]:
a = [[0]*200]*30
for i in range(len(a)):
    a[i][131]=1

b = torch.zeros((30,200,))
b[:,131]=1

In [112]:
[a[i].index(1) for i in range(len(a))]

[131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131,
 131]

In [123]:
torch.where(b==1)

y = "The quick brown fox jumped over the well in my wonderful new era of amazing people coming to see me live while i juggle some balls and deepthoat spaguetti because we love that naked italian pasta with a little tomato sauce and some parmesan with peper [coming out of the closet was not an easy thing and I am starting to think that my whole head is wired around being gay please send help take me out of this hell]"
x = tokenizer.encode(y)


In [129]:

API_START_STR = ' ['
API_END_STR = ']'
DELIMITER_STR = '→'


# create_function_regex():
api_start_regex, api_end_regex = map(
    re.escape, (API_START_STR, API_END_STR))
API_CALL_REGEX = rf'{api_start_regex}.*?{api_end_regex}'


def has_api_calls(text: str):
    matches = re.findall(API_CALL_REGEX, text)
    return len(matches) > 0


def has_api_tokens(data: list):
    try:
        start = data.index(685)
        data.index(60, start)
        return True
    except ValueError:
        # Index excepts if it doesn't find the value
        return False


In [128]:
tokenizer.encode(']')

[60]

In [ ]:
tensor([[1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000,         1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000,         1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.0000],
       [1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000,         1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000,         1.2000, 1.2000, 1.2000, 1.0000, 0.8000, 0.6000]])

tensor([[1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000,         1.2000, 1.2000, 1.2000, 1.2000, 1.0000],
       [1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000,         1.2000, 1.2000, 1.0000, 0.8000, 0.6000]])


In [144]:
import time


times_list = []
times_torch = []

for i in range(1000):
    # Measure time to search for index of element 1 in list a
    start = time.time()
    #a[131] = i
    #c = a.index(1)
    #[a[i].index(1) for i in range(len(a))]

    #d = torch.tensor(a)
    #c = has_api_tokens(x)

    c = [*map(tokenizer.decode, a)]
    times_list.append(time.time()-start)

    # Measure time to search for index of element 1 in torch.tensor b
    start = time.time()
    #b[131] = i
    #c = torch.where(b==1)[0]
    #c = torch.where(b == 1)[0]
    #d = b.tolist()
    #c = has_api_calls(y)

    c = [tokenizer.decode(a[i]) for i in range(len(a))]
    times_torch.append(time.time()-start)


print(f"Average time for list of elements: {sum(times_list)/len(times_list)}")
print(f"Average time for torch tensor: {sum(times_torch)/len(times_torch)}")


Average time for list of elements: 0.037817864418029784
Average time for torch tensor: 0.03810071063041687


In [138]:
[*map(tokenizer.decode, [0])]


['!']

In [152]:
((2==torch.tensor([1,3,3,56,3,4,2,6,4,2,5,6,2,2,2])).cumsum(-1) > 0).cumsum(-1)

tensor([0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [351]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-j-6B")
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")


KeyboardInterrupt: 

In [258]:

generated = model.generate(torch.tensor(gpt2tokenizer.encode("""Your task is to add calls to a Calendar API to a piece of text.
The API calls should help you get information required to complete the text.
You can call the API by writing "[Calendar()]"
Here are some examples of API calls:
Input: Today is the first Friday of the year.
Output: Today is the first [Calendar()] Friday of the year.
Input: The president of the United States is Joe Biden.
Output: The president of the United States is [Calendar()] Joe Biden.
Input: The current day of the week is Wednesday.
Output: """)).unsqueeze(0),
               do_sample=False,
               top_k=50,
               max_length=400,
               top_p=0.95)
print(generated)






The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[ 7120,  4876,   318,   284,   751,  3848,   284,   257, 26506,  7824,
           284,   257,  3704,   286,  2420,    13,   198,   464,  7824,  3848,
           815,  1037,   345,   651,  1321,  2672,   284,  1844,   262,  2420,
            13,   198,  1639,   460,   869,   262,  7824,   416,  3597, 12878,
          9771,  9239,  3419, 30866,   198,  4342,   389,   617,  6096,   286,
          7824,  3848,    25,   198, 20560,    25,  6288,   318,   262,   717,
          3217,   286,   262,   614,    13,   198, 26410,    25,  6288,   318,
           262,   717,   685,  9771,  9239,  3419,    60,  3217,   286,   262,
           614,    13,   198, 20560,    25,   383,  1893,   286,   262,  1578,
          1829,   318,  5689, 21010,    13,   198, 26410,    25,   383,  1893,
           286,   262,  1578,  1829,   318,   685,  9771,  9239,  3419,    60,
          5689, 21010,    13,   198, 20560,    25,   383,  1459,  1110,   286,
           262,  1285,   318,  3583,    13,   198, 2


gpt2tokenizer.decode(generated)

In [ ]:
def calll(some):
    some(' [')
calll(gpt2tokenizer.encode)


[685]

In [266]:


generated = model(torch.tensor(gpt2tokenizer.encode("Hello, I'm a little bit  ")).unsqueeze(0), return_dict = False)

sample = gumbel_sample(generated[0], temperature=0)

gpt2tokenizer.decode(sample[0])


", I'm a little bit oficky "

In [178]:
generated[0].shape

torch.Size([1, 5, 50257])

In [ ]:
import torch

from toolformer import (
    Toolformer,
    PaLM,
    filter_tokens_with_api_response
)

# model

palm = PaLM(
    dim=512,
    num_tokens=20000,
    depth=2,
    heads=8,
    dim_head=64
)

# mock some tokens

mock_start_pos = 512
mock_api_call_length = 10
mock_api_start_id = 19998
mock_api_stop_id = 19999

tokens = torch.randint(0, 20000, (10, 1024))
tokens_with_api_response = torch.randint(0, 20000, (10, 1024))
tokens_without_api_response = torch.randint(0, 20000, (10, 1024))

tokens_with_api_response[:, mock_start_pos] = mock_api_start_id
tokens_with_api_response[:, mock_start_pos +
                         mock_api_call_length] = mock_api_stop_id

tokens_without_api_response[:, mock_start_pos] = mock_api_start_id
tokens_without_api_response[:, mock_start_pos +
                            mock_api_call_length] = mock_api_stop_id

# filter

filtered_results = filter_tokens_with_api_response(
    model=palm,
    tokens=tokens,
    tokens_with_api_response=tokens_with_api_response,
    tokens_without_api_response=tokens_without_api_response,
    filter_threshold=1.,
    api_start_token_id=mock_api_start_id,
    api_end_token_id=mock_api_stop_id
)


TypeError: filter_tokens_with_api_response() missing 1 required keyword-only argument: '__beartype_object_2519220931760'

In [7]:
tokens


tensor([[16756, 11169,     7,  ...,  8491,  9478,  4724],
        [18024, 10254, 12160,  ...,  4099, 16059,   416],
        [15490, 14841,  5138,  ..., 19624, 14182, 13067],
        ...,
        [19918, 12996, 10202,  ...,   799,   288, 13060],
        [18284,  6445,  3069,  ...,  5963,  4224,  6263],
        [ 3653,  1374,  6638,  ..., 15801, 12650, 17566]])

In [64]:
a = "48_augment_database.sh"
for i in a:
    a = "a" + a
    print(i)
    print(a)

print(a)

4
a48_augment_database.sh
8
aa48_augment_database.sh
_
aaa48_augment_database.sh
a
aaaa48_augment_database.sh
u
aaaaa48_augment_database.sh
g
aaaaaa48_augment_database.sh
m
aaaaaaa48_augment_database.sh
e
aaaaaaaa48_augment_database.sh
n
aaaaaaaaa48_augment_database.sh
t
aaaaaaaaaa48_augment_database.sh
_
aaaaaaaaaaa48_augment_database.sh
d
aaaaaaaaaaaa48_augment_database.sh
a
aaaaaaaaaaaaa48_augment_database.sh
t
aaaaaaaaaaaaaa48_augment_database.sh
a
aaaaaaaaaaaaaaa48_augment_database.sh
b
aaaaaaaaaaaaaaaa48_augment_database.sh
a
aaaaaaaaaaaaaaaaa48_augment_database.sh
s
aaaaaaaaaaaaaaaaaa48_augment_database.sh
e
aaaaaaaaaaaaaaaaaaa48_augment_database.sh
.
aaaaaaaaaaaaaaaaaaaa48_augment_database.sh
s
aaaaaaaaaaaaaaaaaaaaa48_augment_database.sh
h
aaaaaaaaaaaaaaaaaaaaaa48_augment_database.sh
aaaaaaaaaaaaaaaaaaaaaa48_augment_database.sh


In [28]:
import re

def length_of_match(pattern, input_string):
    match = re.search(pattern, input_string)
    if match:
        return match.end() - match.start()
    else:
        return 0

def balance_parentheses(string):
    # While there exists "()", remove all ocasions of "()" from the string
    while re.search(r'\(\)', string):
        string = re.sub(r'\(\)', '', string)
    # Find the starting substring that contains only "(" and ")":
    closing_at_start_count = length_of_match(r'^\)+', string)
    if closing_at_start_count > 0:
        string = string[closing_at_start_count:]
    opening_at_start_count = length_of_match(r'^\(+', string)

    opening_at_end_count = length_of_match(r'\(+$', string)
    if opening_at_end_count > 0:
        string = string[:-opening_at_end_count]
    closing_at_end_count = length_of_match(r'\)+$', string)

    remove = min(opening_at_start_count, closing_at_end_count)
    string = string[remove:-remove] if remove > 0 else string

    opening_count = string.count('(')
    closing_count = string.count(')')
    
    diff = opening_count - closing_count
    if diff > 0:
        string = string + ')' * diff
    else:
        string = '(' * diff + string

    if max(opening_count, closing_count) > 0:
        while compensate_match(string):
            string = '(' + string + ')'

    return string

def compensate_match(string):
    # Get the string after the first "(":
    print(string)
    first_open = re.search(r'\(', string)
    if not first_open:
        return re.search(r'\)', string) is not None
    string = string[first_open.end():]

    first = re.search(r'[\(\)]', string)
    if not first:
        return True
    
    if first.group() == '(':
        return compensate_match(string)
    else:
        pending = string[first.end():]
        if len(pending) == 0:
            return False
        
        return compensate_match(pending)

In [29]:
print(balance_parentheses("(1+2)*3)/2"))

In [8]:

from operator import truediv, mul, add, sub

def Calculator(input_query: str, extraargs=None, first=True, detail = False):
    operators = {
        '+': add,
        '-': sub,
        '*': mul,
        '/': truediv
    }
    if first:
        # calc_preprocess_args(input_query) FOR INFERENCE
        # Strip whitespace
        input_query = input_query.replace(" ", "")
        input_query = balance_parentheses(input_query)

    # Handle expressions within parentheses
    while '(' in input_query:
        start = input_query.rindex('(')
        end = start + input_query[start:].index(')')
        sub_expr = input_query[start + 1:end]
        result, op_performed = Calculator(sub_expr, first=False, detail = True)
        first = not op_performed if first else first
        print("Input query: ", input_query)
        input_query = input_query[:start] + str(result) + input_query[end + 1:]
        print("Input query: ", input_query)

    try:
        number = float(input_query)
        if first:
            raise Exception("Useless API call. 1 digit is not a calculation.")
        else:
            print(f"For expression {input_query}, the answer is {number}")
            return (number, False) if detail else number
    except ValueError as e:
        pass

    for c in operators.keys():
        left, operator, right = input_query.partition(c)
        if len(operator) > 0:
            answer = round(operators[operator](Calculator(left, first=False), Calculator(right, first=False)), 2)
            print(f"For expression {input_query}, the answer is {answer}")
            answer = str(answer) if first else answer
            return (answer, True) if detail else answer

In [81]:
balance_parentheses("(1+2)*(3/2")

'1+2)*(3/2))'

In [61]:
def run_calculator_tests():
    test_cases = [
        # Basic arithmetic expressions
        ("2+3*4", 14.0),
        ("(2+3)*4", 20.0),
        ("2+(3+4)*5", 37.0),
        ("1+2*3-4/2", 5.0),

        # Unbalanced parentheses at the start and end
        ("(2+3)*4)", 20.0),
        ("(1+2)*3)/2", 4.5),

        # Unbalanced parentheses in the middle
        ("2+((3+4)*5", 37.0),
        ("((1+2)*3)/2", 4.5),

        # Only opening parentheses at the start
        ("(((((2+3)*4", 20.0),

        # Only closing parentheses at the start
        ("))))2+3)*4", 20.0),

        # Mismatched parentheses
        (")2+3)*4(", 20.0),
        ("((2+3)*4))", 20.0),
        ("((1+2)*3)/2)))", 4.5),

        # No parentheses, basic arithmetic
        ("2+3", 5.0),
        ("3*4", 12.0),
        ("1-2", -1.0),
        ("4/2", 2.0),

        # Complex expression with unbalanced parentheses
        ("(2+(3*4", 14.0),
        ("(1+2)*(3/2", 4.5),
        ("(2+(3*4)-(5/2)+1", 12.5),
    ]

    for expression, expected_result in test_cases:
        try:
            result = Calculator(expression)
            result = float(result)
            assert result == expected_result, f"Expected {expected_result}, got {result}"
            print(f"Test passed: {expression} = {expected_result}")
        except Exception as e:
            print(f"Test failed: {expression}. Error: {e}")
            raise e

run_calculator_tests()

For expression 2, the answer is 2.0
For expression 3, the answer is 3.0
For expression 4, the answer is 4.0
For expression 3*4, the answer is 12.0
For expression 2+3*4, the answer is 14.0
Test passed: 2+3*4 = 14.0
For expression 2, the answer is 2.0
For expression 3, the answer is 3.0
For expression 2+3, the answer is 5.0
Input query:  (2+3)*4
Input query:  5.0*4
For expression 5.0, the answer is 5.0
For expression 4, the answer is 4.0
For expression 5.0*4, the answer is 20.0
Test passed: (2+3)*4 = 20.0
For expression 3, the answer is 3.0
For expression 4, the answer is 4.0
For expression 3+4, the answer is 7.0
Input query:  2+(3+4)*5
Input query:  2+7.0*5
For expression 2, the answer is 2.0
For expression 7.0, the answer is 7.0
For expression 5, the answer is 5.0
For expression 7.0*5, the answer is 35.0
For expression 2+7.0*5, the answer is 37.0
Test passed: 2+(3+4)*5 = 37.0
For expression 1, the answer is 1.0
For expression 2, the answer is 2.0
For expression 3, the answer is 3.0
For

ValueError: substring not found